# Default update config
# Config order: hparams_registry -> config.yaml -> CLI

# SWAD
swad: False #LossValley
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 0.3
test_batchsize: 32
indomain_test: False  # use indomain test split or not
use_lambda_scheduler: True