# Default update config
# Config order: hparams_registry -> config.yaml -> CLI

# SWAD
swad: False #LossValley
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 0.3
test_batchsize: 128
indomain_test: False  # use indomain test split or not

# Contrast settings
use_lambda_scheduler: True
# Linear_cls: False
# backbone: RN50 # 'RN50', 'ViT', 'Reg'
# Text: ViT-B/16 # 'ViT-L/14', 'ViT-B/32'