# Default update config
# Config order: hparams_registry -> config.yaml -> CLI

# SWAD
swad: LossValley
swad_kwargs:
  n_converge: 3
  n_tolerance: 6
  tolerance_ratio: 0.3
test_batchsize: 32
indomain_test: False  # use indomain test split or not

# Contrast settings
# Linear_cls: False
CLIP: False
backbone: RN50 # 'RN50', 'ViT', 'Reg'
# Text: ViT-B/32 # 'ViT-L/14', 'ViT-B/32'